fix(SC2027):

diff --git a/debtap b/debtap
--- a/debtap
+++ b/debtap
@@ -603,11 +603,11 @@ cat tempfile07 | while read line; do
 done
 
 for i in $(eval echo {1..$(cat `ls | grep initial-check-list` | wc -l)}); do
-    if [[ $(sed -n ""$i"{p;q;}" final-check-list | gawk '{print $1}') == "" ]]; then
-		echo $(sed -n ""$i"{p;q;}" `ls | grep initial-check-list`) >> untranslated
-		echo $(sed -n ""$i"{p;q;}" `ls | grep initial-check-list` | gawk '{print $1}') >> untranslated-names-only
-    elif [[ $(echo " $(echo $(grep ^pkgname .PKGINFO | gawk '{print $3}' | sed s'/-svn$\|-git$\|-cvs$\|-bzr$\|-darcs$\|-hg$//'){-svn,-git,-cvs,-bzr,-darcs,-hg,}) " | grep -q " $(sed -n ""$i"{p;q;}" final-check-list | gawk '{print $1}') "; echo $?) == 0 ]]; then
-		echo $(sed -n ""$i"{p;q;}" `ls | grep initial-check-list` | sed s'/ //') >> missing-files
+    if [[ $(sed -n "$i{p;q;}" final-check-list | gawk '{print $1}') == "" ]]; then
+		echo $(sed -n "$i{p;q;}" `ls | grep initial-check-list`) >> untranslated
+		echo $(sed -n "$i{p;q;}" `ls | grep initial-check-list` | gawk '{print $1}') >> untranslated-names-only
+    elif [[ $(echo " $(echo $(grep ^pkgname .PKGINFO | gawk '{print $3}' | sed s'/-svn$\|-git$\|-cvs$\|-bzr$\|-darcs$\|-hg$//'){-svn,-git,-cvs,-bzr,-darcs,-hg,}) " | grep -q " $(sed -n "$i{p;q;}" final-check-list | gawk '{print $1}') "; echo $?) == 0 ]]; then
+		echo $(sed -n "$i{p;q;}" `ls | grep initial-check-list` | sed s'/ //') >> missing-files
     fi
 done
 
